import Head from 'next/head';
import Image from 'next/image';
import Header from '../components/Header';
import UltraJaguar from '../public/UltraJaguar.png';
import { SearchIcon, MicrophoneIcon } from '@heroicons/react/solid';
import Footer from '../components/Footer';
import { useRouter } from 'next/router';
import { useRef } from 'react';
import React from 'react';
import { loadStripe } from '@stripe/stripe-js';

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  function search(event) {
    event.preventDefault();
    const term = searchInputRef.current.value;
    if (!term.trim()) return;
    router.push(`/search?term=${term.trim()}&searchType=`);
  }
  async function randomSearch(event) {
    event.preventDefault();
    const randomTerm = await fetch(
      'https://random-word-api.herokuapp.com/word?number=1'
    ).then((response) => response.json());
    if (!randomTerm) return;
    router.push(`/search?term=${randomTerm}&searchType=`);
  }
  React.useEffect(() => {
    // Check to see if this is a redirect back from Checkout
    const query = new URLSearchParams(window.location.search);
    if (query.get('success')) {
      console.log('Order placed! You will receive an email confirmation.');
    }

    if (query.get('canceled')) {
      console.log(
        'Order canceled -- continue to shop around and checkout when you’re ready.'
      );
    }
  }, []);

  return (
    <div>
      <Head>
        <title>UltraJaguar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <Header />

      <form className="flex flex-col items-center mt-10">
        <Image
          onClick={() => router.push('/')}
          width="1200"
          objectFit="cover"
          height="405"
          className="cursor-pointer"
          src={UltraJaguar}
          alt="Teaching humanity and the animals"
        />
        <section className="flex bg-white dark:bg-gray-900 items-center">
          <div className="container px-6 py-10 mx-auto items-center">
            <div className="lg:flex lg:items-center">
              <div className="w-full space-y-12">
                <div>
                  <h1 className="text-3xl font-semibold text-gray-800 capitalize lg:text-4xl dark:text-white">
                    The Greenest Search engine on the Web
                  </h1>

                  <div className="mt-2">
                    <span className="inline-block w-40 h-1 rounded-full bg-green-600"></span>
                    <span className="inline-block w-3 h-1 ml-1 rounded-full bg-green-600"></span>
                    <span className="inline-block w-1 h-1 ml-1 rounded-full bg-green-600"></span>
                  </div>
                </div>

                <div className="md:flex md:items-start md:-mx-4">
                  <span className="inline-block p-2 text-green-600 bg-green-100 rounded-xl md:mx-4 dark:text-white dark:bg-green-600">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z"
                      />
                    </svg>
                  </span>

                  <div className="mt-4 md:mx-4 md:mt-0">
                    <h1 className="text-2xl font-semibold text-gray-700 capitalize dark:text-white">
                      Fast and Modern
                    </h1>

                    <p className="mt-3 text-gray-500 dark:text-gray-300">
                      Ultra Jaguar is a unique engine created to help people
                      around the world to search and find in the internet what
                      they desire. All of our code uses light weight langauges
                      for fash searchs.
                    </p>
                  </div>
                </div>

                <div className="md:flex md:items-start md:-mx-4">
                  <span className="inline-block p-2 text-green-600 bg-green-100 rounded-xl md:mx-4 dark:text-white dark:bg-green-600">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M14.828 14.828a4 4 0 01-5.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
                      />
                    </svg>
                  </span>

                  <div className="mt-4 md:mx-4 md:mt-0">
                    <h1 className="text-2xl font-semibold text-gray-700 capitalize dark:text-white">
                      Zero Carbon Footprint
                    </h1>

                    <p className="mt-3 text-gray-500 dark:text-gray-300">
                      Ultra Jaguar uses light weight languages and searchs the
                      web without using big hardware that uses excessive
                      electricity.
                    </p>
                  </div>
                </div>

                <div className="md:flex md:items-start md:-mx-4">
                  <span className="inline-block p-2 text-green-600 bg-green-100 rounded-xl md:mx-4 dark:text-white dark:bg-green-600">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M21 15.546c-.523 0-1.046.151-1.5.454a2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.704 2.704 0 00-3 0 2.704 2.704 0 01-3 0 2.701 2.701 0 00-1.5-.454M9 6v2m3-2v2m3-2v2M9 3h.01M12 3h.01M15 3h.01M21 21v-7a2 2 0 00-2-2H5a2 2 0 00-2 2v7h18zm-3-9v-2a2 2 0 00-2-2H8a2 2 0 00-2 2v2h12z"
                      />
                    </svg>
                  </span>

                  <div className="mt-4 md:mx-4 md:mt-0">
                    <h1 className="text-2xl font-semibold text-gray-700 capitalize dark:text-white">
                      Your information, your privacy
                    </h1>

                    <p className="mt-3 text-gray-500 dark:text-gray-300">
                      We don't sell our users data so relax and have Fun
                      searching the web!
                    </p>
                  </div>
                </div>

                <div className="md:flex md:items-start md:-mx-4">
                  <span className="inline-block p-2 text-green-600 bg-green-100 rounded-xl md:mx-4 dark:text-white dark:bg-green-600">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      className="h-6 w-6"
                      fill="none"
                      viewBox="0 0 24 24"
                      stroke="currentColor"
                      strokeWidth="2"
                    >
                      <path
                        strokeLinecap="round"
                        strokeLinejoin="round"
                        d="M4.318 6.318a4.5 4.5 0 000 6.364L12 20.364l7.682-7.682a4.5 4.5 0 00-6.364-6.364L12 7.636l-1.318-1.318a4.5 4.5 0 00-6.364 0z"
                      />
                    </svg>
                  </span>

                  <div className="mt-4 md:mx-4 md:mt-0">
                    <h1 className="text-2xl font-semibold text-gray-700 capitalize dark:text-white">
                      Green Incentives
                    </h1>

                    <p className="mt-3 text-gray-500 dark:text-gray-300">
                      Ultra Jaguar is partnered with over 8+ Institutes in the
                      Amazon Rainforest, and our donations are directed to
                      incentivize intelligent social moviments that will not
                      only refoest trees but also plant new ideas on the amazon
                      societies.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>
      </form>
      <form
        className="flex flex-col items-center pb-12"
        action="/api/checkout_sessions"
        method="POST"
      >
        <button
          className="bg-green-600 hover:bg-green-700 px-10 py-6 font-bold text-white rounded rounded-tr-2xl rounded-bl-2xl"
          type="submit"
          role="link"
        >
          Donate and help the Rainforest!
        </button>
      </form>
      <Footer />
    </div>
  );
}
