import Head from "next/head";
import Image from "next/image";
import AboutHeader from "../components/AboutHeader";
import UltraJaguar from "../public/UltraJaguar.png";
import { SearchIcon, MicrophoneIcon } from "@heroicons/react/solid";
import Footer from "../components/Footer";
import { useRouter } from "next/router";
import { useRef } from "react";

export default function Home() {
  const router = useRouter();
  const searchInputRef = useRef(null);
  function search(event) {
    event.preventDefault();
    const term = searchInputRef.current.value;
    if (!term.trim()) return;
    router.push(`/search?term=${term.trim()}&searchType=`);
  }
  async function randomSearch(event) {
    event.preventDefault();
    const randomTerm = await fetch(
      "https://random-word-api.herokuapp.com/word?number=1"
    ).then((response) => response.json());
    if (!randomTerm) return;
    router.push(`/search?term=${randomTerm}&searchType=`);
  }
  
  return (
    <div>
      <Head>
        <title>UltraJaguar</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>

      <AboutHeader/>

      <form className="flex flex-col items-center mt-40">
        <Image  
        width="1200"
        objectFit="cover"
        height="405"
        src={UltraJaguar}
        alt="Teaching humanity and the animals"
        />
      <section className="flex bg-white dark:bg-gray-900 items-center">
            <div className="container px-6 py-10 mx-auto items-center">
                <div className="lg:flex lg:items-center">
                    <div className="w-full space-y-12">
                        <div>
                            <h1 className="text-3xl font-semibold text-gray-800 capitalize lg:text-4xl dark:text-white">The Greenest Search engine on the Web</h1>
                        
                            <div className="mt-2">
                                <span className="inline-block w-40 h-1 rounded-full bg-green-500"></span>
                                <span className="inline-block w-3 h-1 ml-1 rounded-full bg-green-500"></span>
                                <span className="inline-block w-1 h-1 ml-1 rounded-full bg-green-500"></span>
                            </div>
                        </div>

                        <div className="md:flex md:items-start md:-mx-4">

                            <div className="mt-4 md:mx-4 md:mt-0">
                                <h1 className="text-2xl font-semibold text-gray-700 capitalize dark:text-white">Fast and Modern</h1>

                                <p className="mt-3 text-gray-500 dark:text-gray-300">
                                Ultra Jaguar is a unique engine created to help people around the world to search and find in the internet what they desire. All of our code uses light weight langauges for fash searchs.                                
                                </p>
                            </div>
                        </div>

                        <div className="md:flex md:items-start md:-mx-4">
                            <span className="inline-block p-2 text-green-500 bg-green-100 rounded-xl md:mx-4 dark:text-white dark:bg-green-500">
                                <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6V4m0 2a2 2 0 100 4m0-4a2 2 0 110 4m-6 8a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4m6 6v10m6-2a2 2 0 100-4m0 4a2 2 0 110-4m0 4v2m0-6V4" />
                                </svg>
                            </span>

                            <div className="mt-4 md:mx-4 md:mt-0">
                                <h1 className="text-2xl font-semibold text-gray-700 capitalize dark:text-white">Zero Configrations</h1>

                                <p className="mt-3 text-gray-500 dark:text-gray-300">
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident ab nulla quod dignissimos vel non corrupti doloribus voluptatum eveniet
                                </p>
                            </div>
                        </div>

                        <div className="md:flex md:items-start md:-mx-4">
                            <span className="inline-block p-2 text-green-500 bg-green-100 rounded-xl md:mx-4 dark:text-white dark:bg-green-500">
                                <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17.657 18.657A8 8 0 016.343 7.343S7 9 9 10c0-2 .5-5 2.986-7C14 5 16.09 5.777 17.656 7.343A7.975 7.975 0 0120 13a7.975 7.975 0 01-2.343 5.657z" />
                                    <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.879 16.121A3 3 0 1012.015 11L11 14H9c0 .768.293 1.536.879 2.121z" />
                                </svg>
                            </span>

                            <div className="mt-4 md:mx-4 md:mt-0">
                                <h1 className="text-2xl font-semibold text-gray-700 capitalize dark:text-white">elegant Dark Mode</h1>

                                <p className="mt-3 text-gray-500 dark:text-gray-300">
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Provident ab nulla quod dignissimos vel non corrupti doloribus voluptatum eveniet
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        </form>
    </div>
  );
}
